In [1]:
pip install nltk

Requirement already satisfied: nltk in c:\users\asus\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\asus\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\asus\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\anaconda3\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\asus\anaconda3\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\asus\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install gensim

Requirement already satisfied: gensim in c:\users\asus\anaconda3\lib\site-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in c:\users\asus\anaconda3\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in c:\users\asus\anaconda3\lib\site-packages (from gensim) (1.12.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\asus\anaconda3\lib\site-packages (from gensim) (5.2.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install pyldavis

Requirement already satisfied: pyldavis in c:\users\asus\anaconda3\lib\site-packages (3.4.1)
Requirement already satisfied: numpy>=1.24.2 in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (1.26.4)
Requirement already satisfied: scipy in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (1.12.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (2.2.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (1.4.2)
Requirement already satisfied: jinja2 in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (3.1.4)
Requirement already satisfied: numexpr in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (2.8.7)
Requirement already satisfied: funcy in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (2.0)
Requirement already satisfied: scikit-learn>=1.0.0 in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (1.4.2)
Requirement already satisfied: gensim in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (4.3.3)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from pyldavis) (69.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=2.0.0->pyldavis) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=2.0.0->pyldavis) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=2.0.0->pyldavis) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn>=1.0.0->pyldavis) (2.2.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\asus\anaconda3\lib\site-packages (from gensim->pyldavis) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\anaconda3\lib\site-packages (from jinja2->pyldavis) (2.1.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyldavis) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install wordcloud

Requirement already satisfied: wordcloud in c:\users\asus\anaconda3\lib\site-packages (1.9.3)
Requirement already satisfied: numpy>=1.6.1 in c:\users\asus\anaconda3\lib\site-packages (from wordcloud) (1.26.4)
Requirement already satisfied: pillow in c:\users\asus\anaconda3\lib\site-packages (from wordcloud) (10.3.0)
Requirement already satisfied: matplotlib in c:\users\asus\anaconda3\lib\site-packages (from wordcloud) (3.8.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install textblob

Requirement already satisfied: textblob in c:\users\asus\anaconda3\lib\site-packages (0.18.0.post0)
Requirement already satisfied: nltk>=3.8 in c:\users\asus\anaconda3\lib\site-packages (from textblob) (3.8.1)
Requirement already satisfied: click in c:\users\asus\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\asus\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\asus\anaconda3\lib\site-packages (from nltk>=3.8->textblob) (4.66.4)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from click->nltk>=3.8->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install spacy

Requirement already satisfied: spacy in c:\users\asus\anaconda3\lib\site-packages (3.7.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: language-data>=1.2 in c:\users\asus\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.7.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\asus\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\asus\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.3.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\asus\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\asus\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\users\asus\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install textstat

Requirement already satisfied: textstat in c:\users\asus\anaconda3\lib\site-packages (0.7.4)
Requirement already satisfied: pyphen in c:\users\asus\anaconda3\lib\site-packages (from textstat) (0.16.0)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from textstat) (69.5.1)
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install -U spacy

Requirement already satisfied: spacy in c:\users\asus\anaconda3\lib\site-packages (3.7.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\asus\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: language-data>=1.2 in c:\users\asus\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.7.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\asus\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\asus\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\asus\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.3.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\asus\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\asus\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\users\asus\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install --upgrade pydantic

Requirement already satisfied: pydantic in c:\users\asus\anaconda3\lib\site-packages (2.8.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\asus\anaconda3\lib\site-packages (from pydantic) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\asus\anaconda3\lib\site-packages (from pydantic) (4.11.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import sklearn
import gensim
import pyLDAvis
import wordcloud
import textblob
import spacy
import textstat

In [44]:
news = pd.read_csv("D:/Data Science/abcnews-date-text.csv")

In [46]:
news.head()

   publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

In [48]:
news.tail()

         publish_date                                      headline_text
1082163      20170630  when is it ok to compliment a womans smile a g...
1082164      20170630                   white house defends trumps tweet
1082165      20170630     winter closes in on tasmania as snow ice falls
1082166      20170630  womens world cup australia wins despite atapat...
1082167      20170630          youtube stunt death foreshadowed by tweet

In [50]:
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082168 entries, 0 to 1082167
Data columns (total 2 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   publish_date   1082168 non-null  int64
 1   headline_text  1082168 non-null  object
dtypes: int64(1), object(1)
memory usage: 16.5+ MB

In [52]:
news.describe()

       publish_date
count  1.082168e+06
mean   2.009838e+07
std    3.996017e+04
min    2.003022e+07
25%    2.006113e+07
50%    2.010053e+07
75%    2.013082e+07
max    2.017063e+07