In [1]:
#pandas

import pandas as pd

In [23]:
#creating dat frame using pandas

ages = [10, 20, 45, 25, 66, 97, 100]

pd.DataFrame(ages)

     0
0   10
1   20
2   45
3   25
4   66
5   97
6  100

In [25]:
df_ages = pd.DataFrame(ages)
df_ages.head()
#we can specify a number inside head(). If not it will show the first 5 values

    0
0  10
1  20
2  45
3  25
4  66

In [27]:
#adding name attribute

data = {
    "Name": ["Fahim", "Pranto", "Siyam", "Arif", "Sayem", "Nafi", "Tauhid"],
    "Age": ages
}

print(data)

{'Name': ['Fahim', 'Pranto', 'Siyam', 'Arif', 'Sayem', 'Nafi', 'Tauhid'], 'Age': [10, 20, 45, 25, 66, 97, 100]}

In [29]:
df_sample = pd.DataFrame(data)
#df_sample is a variable name it can be anything

In [33]:
df_sample.head(3)

     Name  Age
0   Fahim   10
1  Pranto   20
2   Siyam   45

In [35]:
df_sample.tail()
#for tail() it will show values from the end

     Name  Age
2   Siyam   45
3    Arif   25
4   Sayem   66
5    Nafi   97
6  Tauhid  100

In [37]:
df_sample.columns

Index(['Name', 'Age'], dtype='object')

In [39]:
df_sample.index

RangeIndex(start=0, stop=7, step=1)

In [41]:
df_sample.set_index("Name", inplace = True)
#it wont show the index anymore

In [43]:
df_sample

        Age
Name
Fahim    10
Pranto   20
Siyam    45
Arif     25
Sayem    66
Nafi     97
Tauhid  100

In [45]:
#EDA = Exploratory Data Analysis
#Collecting data info

df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Fahim to Tauhid
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     7 non-null      int64
dtypes: int64(1)
memory usage: 112.0+ bytes

In [49]:
#summary statistics/ Descriptive statistics
df_sample.describe()
#we can get all kind of statistical value of a dataset by this

              Age
count    7.000000
mean    51.857143
std     36.721604
min     10.000000
25%     22.500000
50%     45.000000
75%     81.500000
max    100.000000

In [51]:
#T format outlook
df_sample.T

Name  Fahim  Pranto  Siyam  Arif  Sayem  Nafi  Tauhid
Age      10      20     45    25     66    97     100

In [53]:
#Doubing ages of first three people
df_sample.multiply(2).head(3)

        Age
Name
Fahim    20
Pranto   40
Siyam    90

In [57]:
#we can also divide

(df_sample/2).head(3)

         Age
Name
Fahim    5.0
Pranto  10.0
Siyam   22.5

In [59]:
#multiplying DF X DF

(df_sample * df_sample).head(4)

         Age
Name
Fahim    100
Pranto   400
Siyam   2025
Arif     625

In [63]:
#check

df_sample < 40

          Age
Name
Fahim    True
Pranto   True
Siyam   False
Arif     True
Sayem   False
Nafi    False
Tauhid  False

In [75]:
#grouping

df_sample.groupby('Name')
print(df_sample.groupby('Name').groups)

{'Arif': ['Arif'], 'Fahim': ['Fahim'], 'Nafi': ['Nafi'], 'Pranto': ['Pranto'], 'Sayem': ['Sayem'], 'Siyam': ['Siyam'], 'Tauhid': ['Tauhid']}

In [77]:
#multi attribute
df_sample.groupby(['Name', 'Age'])
print(df_sample(['Name', 'Age']).groups)

TypeError: 'DataFrame' object is not callable